language: node_js
node_js: "10"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  npm: true
  directories:
    - node_modules

git:
  depth: false

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jobs:
  fast_finish: true
  include:
    - name: Test
      script: npm run puppeter:run

